version: '3.8'

services:

  backend:
    build: ./backend
    ports:
      - 5001:5001
    environment:
      - DATABASE_URL="postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}"
      - SECRET_KEY="${SECRET_KEY}"
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5001", "--reload", "--log-level", "debug"]
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    container_name: "genlib_db"
    environment:
      - POSTGRES_DB="${POSTGRES_DB}"
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"